first-commit
oracle-devrel/kubeflow-oke pull request #1
Opened 2022-08-31 09:57 UTC by julioo

Update documentation to share on KF documentation website

2022-08-31 11:01 UTC, julioo commented
I have read the CLA Document and I hereby sign the CLA

2022-09-01 00:05 UTC, Djelibeybi requested changes
Here is my review. The only thing I strongly encourage is removing any use of third-party tools for security-related stuff, so I took out that bit and provided a script and text instead, that use OpenSSL which is available in Cloud Shell. 

Also, it's considered bad practice to commit commented out code. If it's not needed, remove it. If you need to reference it in future, that's what `git` is for.

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +# Kubeflow-Oke
```suggestion
# Kubeflow for Oracle Container Engine for Kubernetes
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +<!-- ## THIS IS A NEW, BLANK REPO THAT IS NOT READY FOR USE YET.  PLEASE CHECK BACK SOON! -->
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +<!-- toc -->
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    - [Create OKE](#create-oke)
```suggestion
    - [Create an Oracle Container Engine for Kubernetes (OKE) Cluster](#create-oke)
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +Running Kubeflow on [Oracle Container Engine (OKE)][uri-oke].
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +OKE is [Oracle's][uri-oracle] managed [Kubernetes][uri-kubernetes] service on [Oracle Cloud Infrastructure (OCI)][uri-oci].
```suggestion
Oracle Container Engine for Kubernetes (OKE) is the [Oracle][uri-oracle]-managed [Kubernetes][uri-kubernetes] service on [Oracle Cloud Infrastructure (OCI)][uri-oci]. 
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +> ⚠️ Kubeflow 1.5.0 is not compatible with Kubernetes version 1.22 and onwards. To install Kubeflow 1.5.0 and older versions, use OKE v1.21.5.
```suggestion
> ⚠️ Kubeflow 1.5.0 is not compatible with Kubernetes version 1.22 and onwards. To install Kubeflow 1.5.0 or older, set the Kubernetes version of your OKE cluster to v1.21.5.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +This guide explains how to install Kubeflow 1.6.0 on OKE 1.22.5, 1.23.4 and 1.24.1.
```suggestion
This guide explains how to install Kubeflow 1.6.0 on OKE using Kubernetes versions 1.22.5, 1.23.4 and 1.24.1.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +This guide can be run in many different ways, but in all cases, you will need access to an Oracle Cloud Tenancy and be signed in to it.
```suggestion
This guide can be run in many different ways, but in all cases, you will need to be signed into an Oracle Cloud Infrastructure tenancy.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +The steps described below are executed from the Cloud Shell in the OCI console.
```suggestion
This guide uses the [Cloud Shell](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/devcloudshellintro.htm) built into the Oracle Cloud Console but can also be run from your local workstation.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +</summary> -->
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +4. Specify the following configuration details on the Cluster Creation dialog (pay attention to the value you place in the **Shape** field):
```suggestion
4. Specify the following configuration details on the Cluster Creation dialog paying close attention to the value you use in the **Shape** field:
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    * **Name**: The name of the cluster. Accept the default value.
```suggestion
    * **Name**: The name of the cluster. Accept the default value or provide your own.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    * **Compartment**: The name of the compartment. Accept the default value.
```suggestion
    * **Compartment**: The name of the compartment. Accept the default value or provide your own.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    * **Kubernetes API Endpoint**: Determines if the cluster master nodes are going to be routable or not. Select the **Public Endpoint** value.
```suggestion
    * **Kubernetes API Endpoint**: Determines if the cluster control plane nodes will be directly accessible from external sources. Select the **Public Endpoint** value.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    * **Kubernetes Worker Nodes**: Determines if the cluster worker nodes are going to be routable or not. Accept the default value **Private Workers**.
```suggestion
    * **Kubernetes Worker Nodes**: Determines if the cluster worker nodes will be directly accessible from external sources. Accept the default value **Private Workers**.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    * **Shape**: The shape to use for each node in the node pool. The shape determines the number of CPUs and the amount of memory allocated to each node. The list shows only those shapes available i
```suggestion
    * **Shape**: The shape to use for each node in the node pool. The shape determines the number of OCPUs and the amount of memory allocated to each node. The list shows only those shapes available in your tenancy that are supported by OKE.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +<br>
```suggestion

```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    > **Caution**: *VM.Standard.E4.Flex is the recommended shape, but you can adjust based on your requirements and location.*
```suggestion
    > **Caution**: *VM.Standard.E4.Flex is the recommended shape but is not available to Always Free tenancies. You should adjust the shape based on your requirements and location.*
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +  <!-- ![Enter Data](images/ClusterShape2.png) -->
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    > You see the network resources being created for you. Wait until the request to create the node pool is initiated and then click **Close**.
```suggestion
    You see the network resources being created for you. Wait until the request to create the node pool is initiated and then click **Close**.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    > The new cluster is shown on the Cluster Details page. When the master nodes are created, the new cluster gains a status of *Active* (it takes about 7 minutes).
```suggestion
    The new cluster is shown on the Cluster Details page. When the control plane nodes are created, the status of new cluster becomes *Active*. This usually takes around 10 minutes.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    Now your OKE cluster is ready. You can move to Kubeflow installation.
```suggestion
    Now that your OKE cluster is ready, we can move on to the Kubeflow installation.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +
```suggestion
## Install Kubeflow

```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +In this guide, we will use the OCI Cloud Shell console, and all these tools are integrated.
```suggestion
The following utilities are required to install Kubeflow:

- [OCI-CLI](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/cliconcepts.htm)
- [kubectl](https://kubernetes.io/docs/reference/kubectl/)
- [git](https://git-scm.com/)

These tools are installed by default in your Cloud Shell instance.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    - Kubeflow 1.6.0 is not compatible with the latest versions of Kustomize.
```suggestion
> **Warning:** use [Kustomize v3.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0) as Kubeflow 1.6.0 is not compatible with the later versions of Kustomize.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +## Preparation steps
```suggestion
### Preparation
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    - Open the OCI Cloud Shell
```suggestion
    - Open Cloud Shell
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    - Make sure you are in the top level directory
```suggestion
    - Make sure you are in your home directory
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +            cd $HOME
```suggestion
            cd ~
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    - Download Kustomize version 3.2.0 and install in into your OCI Cloud Shell environment.
```suggestion
    - Download Kustomize v3.2.0 and install it in your Cloud Shell environment.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +            curl -L -o kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64
```suggestion
            curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/v3.2.0/kustomize_3.2.0_linux_amd64 -o kustomize
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +2. Clone the Kubeflow repository version 1.6.0 into your OCI Cloud Shell environment
```suggestion
2. Clone the v1.6.0 branch of the Kubeflow manifests repository to your Cloud Shell environment
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +        git clone -b v1.6-branch https://github.com/kubeflow/manifests.git kubeflow_1.6
```suggestion
        git clone -b v1.6-branch https://github.com/kubeflow/manifests.git kubeflow-1.6
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +        cd kubeflow_1.6
```suggestion
        cd kubeflow-1.6
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +        cat common/dex/base/config-map.yaml.org | sed "s|hash:.*|hash: $kubeflow_password|" > common/dex/base/config-map.yaml
```suggestion
3. Replace the default email address and password used by Kubeflow with a randomly generated one:
    
   ```shell
   $ PASSWD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 55 | head -n 1)
   $ KF_PASSWD=$(htpasswd -nbBC 12 USER $PASSWORD| sed -r 's/^.{5}//')
   $ sed -i.orig "s|hash:.*|hash: $KF_PASSWD|" common/dex/base/config-map.yaml 
   $ echo "Random password is: $PASSWD"
   ```
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +        cat common/dex/base/config-map.yaml.org | sed "s|hash:.*|hash: $kubeflow_password|" > common/dex/base/config-map.yaml
The formatting may be a little off on this one, so please double-check!

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +  <!-- > If you installed your cluster using the single-script the access is already set. -->
```suggestion
1. To access your OKE cluster, click **Access Cluster** on the cluster detail page. Accept the default **Cloud Shell Access** and click **Copy** to copy the `oci ce cluster create-kubeconfig ...` command. Next, paste it into your Cloud Shell session and hit **Enter**.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +  You may need to run this command several times until you see an output similar to the following.
```suggestion
  Verify that the `kubectl` is working by using the `get nodes` command. You may need to repeat this command several times until all three nodes show `Ready` in the `STATUS` column.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +  > If you see the node's information, then the configuration was successful.
```suggestion
  When all three nodes are `Ready`, your OKE install has finished successfully.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +        cd $HOME/kubeflow_1.6
```suggestion
        cd $HOME/kubeflow-1.6 
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +> Installation takes about 10 to 15 min.
```suggestion
Installation usually takes between 10 to 15 minutes.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +To check that all Kubeflow-related Pods are ready, use the following commands:
```suggestion
Use the following commands to check if all the pods related to Kubeflow are ready:
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +>It takes about 15 min to have all the containers running.
```suggestion
It usually takes about 15 minutes for all the pods to start successfully.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +Kubeflow v1.6 already deploy a load balancer and expose the dashboard to Internet.
```suggestion
## Accessing the Kubeflow Dashboard

To enable access to the Kubeflow Dashboard from the internet, we first need to change the default `istio-ingressgateway` service created by Kubeflow into a `LoadBalancer` service using the following commands:

```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +Change istio-ingressgateway to LoadBalancer
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    $HOME/keys/step certificate create $External_IP.nip.io tls-$External_IP.crt tls-$External_IP.key --profile leaf  --not-after 8760h --no-password --insecure --kty=RSA --ca $HOME/keys/root.crt --ca
```suggestion
```

Please replace this content with the content from here: https://gist.github.com/Djelibeybi/52ff365ef09e19a05c9df37cfca34b13 which does not rely on any third-party tool to generate certificates.

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +    $HOME/keys/step certificate create $External_IP.nip.io tls-$External_IP.crt tls-$External_IP.key --profile leaf  --not-after 8760h --no-password --insecure --kty=RSA --ca $HOME/keys/root.crt --ca
This is also available as a script that will generate the certificates for you: https://gist.github.com/Djelibeybi/0ad564baa715045dc9feea69e7113086

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +        kubectl create secret tls kubeflow-tls-cert --key=tls-$External_IP.key --cert=tls-$External_IP.crt -n istio-system
```suggestion
  * Create a Kubernetes Secret to store the certificate

        cd $HOME/kubeflow-ssl
        kubectl create secret tls kubeflow-tls-cert --key=$DOMAIN.key --cert=$DOMAIN.crt -n istio-system    
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +  * Update Kubeflow API Gateway
```suggestion
  * Update the Kubeflow API Gateway definition
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +Congratulations you installed Kubelow on OKE.
```suggestion
Congratulations! You have successfully installed Kubeflow on your OKE cluster.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +Access $External_IP.nip.io
```suggestion
Visit https://<Load Balancer External IP>.nip.io to access the Kubeflow Dashboard.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +MISSING -->
```suggestion
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
> +www.kubeflow.org
```suggestion

Kubeflow: <https://www.kubeflow.org/>
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
>  This project is open source.  Please submit your contributions by forking this repository and submitting a pull request!  Oracle appreciates any contributions that are made by the open source communi
```suggestion
Oracle appreciates any contributions that are made by the community. Please submit your contributions by forking this repository and submitting a pull request. Opening an issue to discuss your contribution beforehand, especially if it's a new feature, would be appreciated.
```

2022-09-01 00:05 UTC, Djelibeybi commented on README.md
>  Licensed under the Universal Permissive License (UPL), Version 1.0.
```suggestion
Copyright (c) 2022 Oracle and/or its affiliates.

Licensed under the Universal Permissive License (UPL), Version 1.0 as shown at https://opensource.oracle.com/licenses/upl/
```

2022-09-01 08:02 UTC, Djelibeybi commented
BTW, I encourage you to use https://github.com/markdownlint/markdownlint to check your Markdown syntax. There is a Visual Studio Code plugin that embeds it to make it really easy to use.

2022-09-02 09:25 UTC, snafuz approved these changes

2022-09-02 09:26 UTC, merged