Installation1 6
oracle-devrel/kubeflow-oke pull request #2
Opened 2022-09-02 15:06 UTC by julioo

2022-09-02 22:51 UTC, Djelibeybi requested changes

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +This guide explains how to install Kubeflow 1.6.0 on OKE using Kubernetes versions 1.22.5, 1.23.4 and 1.24.1 and image Oracle Linux 7.9.
```suggestion
This guide explains how to install Kubeflow 1.6.0 on OKE using Kubernetes versions 1.22.5, 1.23.4 and 1.24.1 running on Oracle Linux 7.
```

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +The following steps are designed to work without any editing but will used default values for `C` (country), `ST` (state), `L` (location), `O` (organization) and `OU` (organizational unit) fields. Fe
```suggestion
The following steps are designed to work without any editing but will use default values for `C` (country), `ST` (state), `L` (location), `O` (organization) and `OU` (organizational unit) fields. Feel free to edit these default values.
```

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +To generate a SSL certificate, you can use OCI Certificates your own provider, or create a sefl-signed certificate using the following [script](generate-kubeflow-cert.sh) and steps detailled below.
```suggestion
To generate a SSL certificate, you can use OCI Certificates, your own provider, or create a self-signed certificate using the [`generate-kubeflow-cert.sh` script](generate-kubeflow-cert.sh) or by following the steps below.

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +To enable HTTPS on Istio IngressGateway you need to generate a SSL certificate.
```suggestion
To enable HTTPS for the Istio ingress gateway you need to generate a SSL certificate.
```

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +<details><summary><b>Click to details self-signed certificate</b></summary>
```suggestion
<details><summary><b>Click for details on creating a self-signed certificate</b></summary>
```

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +- Create a Kubernetes Secret to store the certificate
```suggestion
- Create a Kubernetes secret to store the certificate
```

2022-09-02 22:51 UTC, Djelibeybi commented on README.md
> +Store the certificate as a Kubernetes TLS Secret in istio-system namespace.
```suggestion
Store the certificate as a Kubernetes TLS secret in the `istio-system` namespace.
```

2022-09-05 11:44 UTC, Djelibeybi approved these changes

2022-09-06 09:56 UTC, snafuz approved these changes

2022-09-06 09:57 UTC, merged